In [62]:
# Michael Glushchenko, HW1 Python Code, CS111 F21

import sys
sys.path.append("/Users/Mike/desktop/UCSB/CS/CS111/cs111-2021-fall") 

import os
import time
import math
import numpy as np
import numpy.linalg as npla

import matplotlib
%matplotlib ipympl
import matplotlib.pyplot as plt

np.set_printoptions(precision = 4)

### Problem 1

In [97]:
A = np.array([[3, -1, 2], [0, 1, 2], [1, 0, -1]]) # matrix A for problem 1
print("A transpose: \n", A.T) # A^T
print("A squared: \n", A @ A) # A^2
print("A transpose times A: \n", (A.T) @ (A)) # (A^T)*A

A transpose: 
 [[ 3  0  1]
 [-1  1  0]
 [ 2  2 -1]]
A squared: 
 [[11 -4  2]
 [ 2  1  0]
 [ 2 -1  3]]
A transpose times A: 
 [[10 -3  5]
 [-3  2  0]
 [ 5  0  9]]


### Problem 2

In [87]:
x = np.array([3, 1, 4, 1, 5]) # vector x for problem 2
print("The Eucledean norm of vector x is: ", np.linalg.norm(x)) # problem 2 answer

The Eucledean norm of vector x is:  7.211102550927978


### Problem 3

In [88]:
A = np.array([[2, 3, 1], [0, 2, 3], [0, 1, 1]]) # matrix A for problem 3
b = np.array([1, 7, 4]) # vector b for problem 3

### Problem 4

In [89]:
x = npla.solve(A, b) # solution vector x solves Ax = b
print("The solution to Ax = b is: ", x) # problem 4 answer

The solution to Ax = b is:  [-6.5  5.  -1. ]


In [92]:
print(np.array_equal(b, A @ x)) # to confirm our answer

True
